<?php

namespace Tops\particles\tops;

use pocketmine\world\Position;

class DefaultTopParticle extends BaseTopParticle
{
    public function __construct(Position $position, string $index)
    {
        $this->setInfo();
        parent::__construct($position, $index);
    }

    public function setInfo(): void {
        $list = [
            'nad543' => rand(0, 100000),
        ];

        $this->setList($list);
    }

    public function setList(array $list): void
    {
        parent::setList($list); // TODO: Change the autogenerated stub
    }
}